name: deploy

on: push

jobs:
  build:
    name: npm deploy to github pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: npm deploy
        run: |
          npm run deploy