name: deploy

on: push

jobs:
  build:
    name: npm deploy to github pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Build with npm
        run: |
          npm install
          npm run build

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d dist -u "github-actions-bot <support+actions@github.com>" --cname flix29.de
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}